 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/players", type: :request do
  before do
    Rails.application.env_config["devise.mapping"] = Devise.mappings[:admin] # If using Devise
    Rails.application.env_config["omniauth.auth"] = OmniAuth.config.mock_auth[:google]

    if (Admin.where(email: "johndoe@example.com").first.nil? == true)
      Admin.create(email: "johndoe@example.com", full_name: "View Players Test", uid: "123abc456", avatar_url: "www.example.com")
    end
  end
  # Player. As you add validations to Player, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {{
    "admin_id" => Admin.where(email: "johndoe@example.com").first.id,
    "name" => "Name",
    "played" => 5,
    "wins" => 3,
    "strengths" => "MyText",
    "weaknesses" => "MyText",
    "additional_info" => "MyText"
  }}

  let(:invalid_attributes) {{
    "admin_id" => Admin.where(email: "johndoe@example.com").first.id,
    "name" => "Texas A&M",
    "played" => 2,
    "wins" => 10,
    "strengths" => "",
    "weaknesses" => "MyText",
    "additional_info" => "MyText"
  }}

  describe "GET /index" do
    it "renders a successful response" do
      Player.create! valid_attributes
      get players_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      player = Player.create! valid_attributes
      get player_url(player)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_player_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      player = Player.create! valid_attributes
      get edit_player_url(player)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Player" do
        expect {
          post players_url, params: { player: valid_attributes }
        }.to change(Player, :count).by(1)
      end

      it "redirects to the created player" do
        post players_url, params: { player: valid_attributes }
        expect(response).to redirect_to(player_url(Player.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Player" do
        expect {
          post players_url, params: { player: invalid_attributes }
        }.to change(Player, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post players_url, params: { player: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested player" do
        player = Player.create! valid_attributes
        patch player_url(player), params: { player: new_attributes }
        player.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the player" do
        player = Player.create! valid_attributes
        patch player_url(player), params: { player: new_attributes }
        player.reload
        expect(response).to redirect_to(player_url(player))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        player = Player.create! valid_attributes
        patch player_url(player), params: { player: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested player" do
      player = Player.create! valid_attributes
      expect {
        delete player_url(player)
      }.to change(Player, :count).by(-1)
    end

    it "redirects to the players list" do
      player = Player.create! valid_attributes
      delete player_url(player)
      expect(response).to redirect_to(players_url)
    end
  end
end
